version: '3.8'

services:
  react-admin:
    image: node:20-alpine
    container_name: immo-admin-react
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
