version: '3.8'

services:
  vue-client:
    image: node:20-alpine
    container_name: immo-client-vue
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
